services:
  api:
    container_name: debesis_api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

    ports:
      - 8000:8000

    env_file:
      - .env

    depends_on:
      - db
      - redis


  redis:
    container_name: debesis_redis
    image: redis:alpine


  celery:
    container_name: debesis_celery
    build: .
    command: celery -A debesisAPI worker --loglevel=info

    env_file:
      - .env

    depends_on:
      - api
      - redis

  db:
    container_name: debesis_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432

    env_file:
      - .env

volumes:
  postgres_data: